### PR TITLE
Szit typo

### PR DESCRIPTION
**Pull request by anwolosz**
@jano-wol 
Please check.
Do I know well, that all of these typo occurred in the physical book too, right?

### CODE REVIEW

**Comment by anwolosz** [comment]
I messed up the PR, KNB change has it's own PR...
Please check those for details: https://github.com/anwolosz/synopsis/pull/134

**Comment by jano-wol** [comment]
> @jano-wol Please check. Do I know well, that all of these typo occurred in the physical book too, right?

All three typos are presented in the physical book too.

**Comment by jano-wol** [comment]
> I messed up the PR, KNB change has it's own PR... Please check those for details: #134

I checked the KNB PR and had some discussion on it. Its okay as it is, but we would prefer to do changes only for:
- rámtekintett
- papnakés
- királynőjeföl 
- királynőjefelkel
- gyalázatott
- szövetségaz

The others could go to the "notes" section.

**Comment by anwolosz** [comment]
Okok, please check commit: https://github.com/anwolosz/synopsis/commit/f8a27475a072605f8407e7bfbd3d6f2135fd338b

**Pull request merged**
