### PR TITLE
Improve toLeading.json

### PR DESCRIPTION
**Pull request by jano-wol**

### CODE REVIEW

**Review by anwolosz — COMMENTED** [review]
"lk17,3" is really a poor referencing.
But the other three is not that bad. I guess you don't like the section title mismatching. Even though it's distracting I'm not sure if it's really a "wrong" reference. Talk about it sometime.

**Comment by jano-wol** [comment]
OK lets discuss this PR.

**Comment by jano-wol** [comment]
Closing PR. Final decision will be done in:
https://github.com/anwolosz/synopsis/issues/69

**Comment by jano-wol** [comment]
Final decision will be done in:
https://github.com/anwolosz/synopsis/issues/69

**Pull request closed without merging**
